import { IsString, IsNotEmpty, Length, IsOptional, IsEnum } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { ShipmentStatus } from '@prisma/client'; // This is generated by your Docker step

export class CreateShipmentDto {
  @IsString()
  @IsNotEmpty()
  @Length(3, 50)
  trackingId: string;

  @IsString()
  @IsNotEmpty()
  @Length(2, 200)
  origin: string;

  @IsString()
  @IsNotEmpty()
  @Length(2, 200)
  destination: string;

  @ApiPropertyOptional({ enum: ShipmentStatus })
  @IsOptional()
  @IsEnum(ShipmentStatus)
  status?: ShipmentStatus;
}
